### ISSUE TITLE
Doesn't work on distros with Python3 as default python version

### ISSUE THREAD

**Issue by MaikuMori** [sourcegraph/srclib-python#18]
Some distros (Archlinux for example) have Python 3 as default python version. So when install calls `pip` command, it will install dependencies in python 3 global environment. Also `/usr/bin/python` points to Python 3 binary.

Best fix would be to create virtualenv for srclib-python and install dependencies there. This would also benefit people with older python 2 as it would not litter global environment with extra packages and it would remove the need for `sudo`.

Example error:

```
Running: [/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python scan --repo github.com/MaikuMori/sourcegraph-atom --subdir .]
  --> with input {}
  File "/usr/bin/pydep-run.py", line 54
    print json.dumps(setup_infos)
             ^
SyntaxError: invalid syntax
EOF
```

**Comment by beyang** [comment]
Yeah, this is a good idea. Currently, we've only tested with Python 2.7. We're currently bottlenecked on dev resources, though, so it might take us awhile to get to this, unfortunately.
