### ISSUE TITLE
Instance variable defs and refs are incorrect

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-python#63]
Consider `class Class0` in https://sourcegraph.com/github.com/sgtest/python-sample-0/-/blob/pkg0/m0.py.

The 2 assignments to `self.var1` are given separate names (`pkg0/m0.py/m0.Class1.__init__.var1` and `pkg0/m0.py/m0.Class1.meth0.var1`).

1. These names should be the same.
2. The name should differentiate between the `var1` instance variable and a local variable named `var1`.
3. The second assignment should be treated as a non-definitional reference. The first assignment is the definition. (Alternatively, we could modify the srclib schema to allow multiple definitional references for a single definition).

**Comment by Unknwon** [comment]
Note:

Currently this issue seems already fixed (from local instance)

![image](https://cloud.githubusercontent.com/assets/2946214/16459705/74199812-3e56-11e6-8665-573d146fe7bb.png)
