### ISSUE TITLE
Python token highlighting is off

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-python#65]
See https://sourcegraph.com/github.com/pallets/flask@4f83f705e7a5f35381841148caf04b2829873faf/-/blob/flask/__main__.py

![image](https://cloud.githubusercontent.com/assets/1646931/16018528/ac133f3e-3159-11e6-938f-289e6aa99be7.png)

**Comment by alexsaveliev** [comment]
It seems related to https://app.asana.com/0/87040567695724/143652758316943
Works properly on my local instance
